### ISSUE TITLE
How would I make so other people in other computers could connect to the chat?

### ISSUE THREAD

**Issue by notsonsi** [Drakirus/java-chat#3]
I suppose that with this server people that are using other computers wouldn't be able to connect to the chat since the server is local right?

How would I make so other people in other computers could connect to the chat?

**Comment by pchampio** [comment]
https://stackoverflow.com/questions/14976867/how-can-i-bind-serversocket-to-specific-ip
with 
```
new ServerSocket(12345, 50, InetAddress.getByName("0.0.0.0"));
```
here:
https://github.com/pchampio/java-chat/blob/8fd7d42a53e507933f7138ed7bad7deba9631094/Server.java#L30

and the IP of the server instead of local host here:
https://github.com/pchampio/java-chat/blob/8fd7d42a53e507933f7138ed7bad7deba9631094/Client.java#L17

**Comment by notsonsi** [comment]
Sorry to bother you but do you have a video or link that explains how would I create a server or some program that does that for me?
